### ISSUE TITLE
Use @fluent/dedent

### ISSUE THREAD

**Issue by stasm** [eemeli/fluent-compiler#1]
Hi @eemeli 👋 I noticed that you implemented a dedentation helper in: https://github.com/eemeli/fluent-compiler/blob/63c40ff2df0261a7684434c8e23de3bc4f4766e0/test/util.js#L16-L24

Not too long ago I extracted and refactored the `ftl` helper into its own package: https://github.com/projectfluent/fluent.js/tree/master/fluent-dedent

Perhaps you'd like to switch to it? I can create a pull request, if you wish.

**Comment by eemeli** [comment]
Sure, I'm fine with switching, and would welcome a PR.

FYI, the dedenter is only used in the tests, and it probably cleans up leading & trailing empty lines a bit differently than `@fluent/dedent`. I also just pushed a bunch of changes that bring the implementation in line with projectfluent/fluent.js#380, in case you start working on this.
